### ISSUE TITLE
multiple sensors

### ISSUE THREAD

**Issue by jborget** [matthewwall/weewx-interceptor#11]
I'm currently experiencing a problem where one of my neighbors has recently purchased an acurite tower sensor that my acurite bridge is picking up and reporting.  I'm currently using the weewx-interceptor plugin for the acurite-bridge using the sniff mode with a pcap filter.  I can't seem to properly exclude their tower sensor using the sensor_map in the weewx.conf, perhaps I'm doing something wrong.  I'm using the Acurite 5n1 sensor and is the only sensor I want to be receiving data from.  I can see both sensor names when running the debug output from the interceptor.py script from command line.  I tried to specify inTemp and outTemp using the temperature sensor names but each time I try it I don't get any data reported.   Any suggestion on how to easily exclude a sensor or only report data from a specific sensor?  

Thanks.

**Comment by matthewwall** [comment]
each sensor detected by an acurite bridge has an identifier with this pattern:

<observation_name>.<sensor_identifier>.<bridge_identifier>

the sensor_identifier for your 5n1 should be different from the identifier for the tower.  so you should see something like:

```
temperature.yyyyyy.xxxx
temperature.zzzzz.xxxx
```

where yyyyyy is the identifier for your 5n1 and zzzzzz is the identifier for your neighbor's tower, and xxxx is the mac address of your bridge.

so you want a sensor_map entry like this:

```
[Interceptor]
    [[sensor_map]]
        outTemp = temperature.yyyyyy.*
```

that should ignore your neighbor's zzzzzz sensor.

if you're still having problems, please post to the weewx user group:

`http://groups.google.com/group/weewx-user`

along with the configuration that you are using.
