### ISSUE TITLE
Trouble with pcap_filter when trying to run Interceptor directly on OS X

### ISSUE THREAD

**Issue by pmccurdypac** [matthewwall/weewx-interceptor#16]
Fresh install of weewx and interceptor on OSX.

Install runs fine, but when I try to run Interceptor directly, I get:

interceptor.py: error: no such option: --pcap_filter

OSX 10.10.5
Python 2.7.10
weewx 3.7.0
Interceptor downloaded today
pypcap 1.1.5

Thanks for any help.

Patrick

**Comment by matthewwall** [comment]
try `--pcap-filter`

**Comment by matthewwall** [comment]
try `--filter`

use `--help` to see the options
