### ISSUE TITLE
No data on my weewx site

### ISSUE THREAD

**Issue by Blisk** [matthewwall/weewx-interceptor#18]
I have installed weewx on my web server which is on public IP and weewx listen on port 9999
if I run from differend PCs on differend locations, http://mywebsite.com:9999 I get "success" and I can see in log that weewx responsed.
Also I have configured my weather Ranger to port 9999 which is on my local network at home.
I get no data on weewx server. But weather station send data to wunderground with no problem.
What can be wrong?

[Menu]
default=www.wunderground.com
web=2
web1=www.wunderground.com
web2=mywebsite.com

[www.wunderground.com]
Server=www.wunderground.com
ServerType=php
ServerPort=80
UploadType=Customize
ReadOnly=true

[mywebsite.com ]
Server=mywebsite.com
ServerType=php
ServerPort=9999
UploadType=Customize
ReadOnly=true

**Comment by matthewwall** [comment]
you need to verify that the weather station is actually sending data to mywebsite.com:9999 and that it is not being blocked/dropped somewhere

do a packet capture of the traffic from the weather station

on a computer that is on the same network segment as the weather station (or on the router that the weather station goes through), do a tcpdump like this:
```
tcpdump -i iface src x.x.x.x
```
where iface is the network interface of the machine on which tcpdump is running and x.x.x.x is the ip address of the weather station.
