### ISSUE TITLE
Acurite Access - smartHub replacement

### ISSUE THREAD

**Issue by tinso** [matthewwall/weewx-interceptor#25]
Hi, I got the new replacement for the smartHub from Acurite. I plugged in to the raspberry Pi which is running the weewx-interceptor but they changed a bit how it send the data now. I ran weewx in debug mode and capture the data to a file. I know nothing about python so I'm unable to fix it and give it to you. But if you're willing to work with me to add this to the interceptor I can provide you with all the data I have gather so far and whatever you might need in the future. Will you?

**Comment by matthewwall** [comment]
happy to sort this out if you have not done so already.  better if you post to the weewx-user group first.  then others can help/benefit too.  use this issue tracking system if there is a specific change/feature we need to make to the weewx-interceptor code.
