### ISSUE TITLE
Exceptions attribute error - Acurite bridge

### ISSUE THREAD

**Issue by logname** [matthewwall/weewx-interceptor#27]
Have installed weeWX on MacOS 10.11.6 and I think my install is correct. I'm able to launch with Simulator configured, but I get the following error when I try to run configured with Interceptor for an Acurite bridge.

I also installed libcap as instructed. 

5/24/18 1:12:59.654 AM weewx[677]: import of driver failed: 'module' object has no attribute 'pcapObject' (<type 'exceptions.AttributeError'>)
5/24/18 1:12:59.655 AM weewx[677]: engine: Unable to load driver: 'module' object has no attribute 'pcapObject'
5/24/18 1:12:59.655 AM weewx[677]:     ****  Exiting...

From my conf file...

[Interceptor]
    # This section is for the network traffic interceptor driver.

    # The driver to use:
    driver = user.interceptor

    # Specify the hardware device to capture.  Options include:
    #   acurite-bridge - acurite internet bridge
    #   observer - fine offset WH2600/HP1000/HP1003, aka 'observer'
    #   lw30x - oregon scientific LW301/LW302
    #   lacrosse-bridge - lacrosse GW1000U/C84612 internet bridge
    device_type = acurite-bridge
    mode = sniff
    iface = eth1
    pcap_filter = src 192.168.0.125 and dst port 80

Not sure where to go from here. I know nothing about python. Have not reached out to the google group yet, but I thought perhaps the author would be a better start. Any guidance would be much appreciated.

**Comment by matthewwall** [comment]
that smells like a pcap version/api issue.  please post this to the weewx-user group and i will respond with instructions there.  that way anyone else with the same issue can benefit.  use this issue list once/if we identify a specific problem with the weewx-interceptor code.
