### ISSUE TITLE
remapping sensor on driver interceptor for wethaer station wh-2650

### ISSUE THREAD

**Issue by icnmfabro** [matthewwall/weewx-interceptor#41]
Hello.
I would like to modify the sensor map of a WH-2650 on the interceptor driver, so that the internal sensor placed on a solar screen acts as an external thermo-hygrometer sensor.
Clearly the external sensor of the wh-2650 must be redirected as an internal sensor or at most must return null values.
 Any idea of ​​how to do it? have you already changed the sensor map of the Interceptor?

**Comment by matthewwall** [comment]
this is for bug reports.  and you already cross-posted on weewx-user and weewx-development forums anyway, despite that cautions against it.
