### ISSUE TITLE
Problem with the WH-2650 bridge after firmware update

### ISSUE THREAD

**Issue by icnmfabro** [matthewwall/weewx-interceptor#47]
Hello matthewwall.

I did a firmware update of my Waldbeck Halley WH-2650 bridge, bringing it to version 1.4.6. I state that until the previous version 1.4.5 everything worked correctly, now I find myself the bridge that is no longer seen by the Interceptor driver.
By executing the tcpdumb command, I can intercept the bridge but I no longer see the GET HTTP cheamte of the Wunderground protocol.
Below you will find a segment of the saved stream, I would like to know if it is possible to use the Interceptor again to capture the data and process it with Weewx.

Sincerely.

[log.txt](https://github.com/matthewwall/weewx-interceptor/files/3081615/log.txt)

**Comment by matthewwall** [comment]
this is for reporting bugs

please post your question at the weewx user group at google groups
