### ISSUE TITLE
extraHumid1 mapped but not in DB

### ISSUE THREAD

**Issue by wwray** [matthewwall/weewx-interceptor#49]
Hi there, I have an acurite bridge successfully reporting via weewx, but I'm having a problem mapping both my towers. The intemp and inhumidity is working and the extratemp1 is being reflected but my extrahumid1 has a column in the weewx db and is being mapped by interceptor but no data is being recorded in the archive table. 

Can you help please? Thanks,

**Comment by matthewwall** [comment]
this is for reporting bugs

please post your question at the weewx users group at google groups
