### ISSUE TITLE
Froggit WH6000 and wu-client

### ISSUE THREAD

**Issue by ocellz** [matthewwall/weewx-interceptor#50]
Hello I'm a newbie with WeeWX. I'm trying to capture the data from my new WH6000 from Froggit (I can assume is a Fine Offset but I'm not sure). Its console sends data directly to WU using rtupdate.wunderground.com, so I think that the interceptor with device=wu-client should read its data but I'm having problems configuring this.
I have some questions: The unique example for wu-client is in mode sniff and interface eth0. I'm setting up weewx on a RaspberryPi 3 B+, so my interface will be wlan0. I try to test it with this command:
`PYTHONPATH=bin python bin/user/interceptor.py --device=wu-client --mode=sniff --iface=wlan0 --filter="src 192.168.1.105 and dst port 80"`

But I'm getting this error:
`Exception: wlan0: You don't have permission to capture on that device (socket: Operation not permitted)`

Should I always try sniff? In listen mode won't it work? What port should I use? I've tried it but I'm getting another error.
`PYTHONPATH=bin python bin/user/interceptor.py --device=wu-client --mode=listen --port=80`

`  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied`

I'm stuck with this. What should i try?
Thanks

**Comment by matthewwall** [comment]
support questions should be posted at the weewx user group at google groups
