### ISSUE TITLE
Trouble with interceptor

### ISSUE THREAD

**Issue by Blisk** [matthewwall/weewx-interceptor#56]
I had problem with weewx and interceptor.
My weatherstation is at home and server with weewx is on other location.
All worked great until april 5th, when suddenly stops to work.
First I try to solve this with weewx google group and didn't worked, so I had to reinstall new server centos 7.6 with fresh installation of weewx and problem was the same no data and no logs.
Now we finally find out that centos 7.6 log must be setup for debug.
I did that and now I have logs but there is no data. All worked before with same settings but now not anymore. Can someone help me with this please?

Jun 16 09:37:13 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:37:23 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:37:33 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:37:43 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:37:53 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:38:03 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:38:13 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:38:23 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:38:33 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:38:43 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:38:53 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:39:03 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:39:13 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:39:23 povej weewx[503]: interceptor: MainThread: empty queue
Jun 16 09:39:33 povej weewx[503]: interceptor: MainThread: empty queue

**Comment by matthewwall** [comment]
this is for reporting bugs.  for help configuring and using, please go to the weewx user group
