### ISSUE TITLE
Acurite Access = WeeWX Interceptor

### ISSUE THREAD

**Issue by ZXant** [matthewwall/weewx-interceptor#57]
Matthew

As always, too many hours already trying to make WeeWX on RasperryPi to connect to Acurite Access, at no result (1st try normal installation; 2nd try driver standalone; etc).

Acurite Access has a Static DHCP through DD-WRT router. The following command, returns no result:

PYTHONPATH=/usr/share/weewx python /usr/share/weewx/user/interceptor.py --device=acurite-bridge --mode=sniff --iface=eth0 --filter="src 192.168.1.135 and dst port 80"

Understand there might be other 'strong' approaches (DNS hijack, direct eth0 connection, etc). Please, advice whats "next" and usually works for WeeWX Interceptor and Acurite Access.

Thanks, ZX

**Comment by jrhelbert** [comment]
I'm pretty sure the interceptor driver isn't compatible with the Access. Starting with the Access, Acurite sends all the data to their servers using https (or some other form of encrypting protocol) that by design you cant sniff or intercept.

**Comment by ZXant** [comment]
Hmmmm... interesting. Thanks Jrhelbert

After much plus hours, I was able to DNS hijack "atlasapi.myacurite.com" (this is the "new" API/myacurite.com address) to RaspberryPi/WeeWX IP address through DD-WRT DNSmasq/DNS Forwarding... still, no luck and stuck. 

Is this a losing battle as Jrhelbert said ("some form of encrypting protocol to their servers")?

If so... should forget about Acurite Access and get any display device, with USB port, that may recognize Atlas? If so, advice/suggestions?

Interesting enough, WeeWX hardware compatibility page does list Acurite Atlas/Access as compatible.

![image](https://user-images.githubusercontent.com/53246705/61838886-5ef5cc00-ae59-11e9-8915-756d45856c02.png)


Thanks, ZXant

**Comment by matthewwall** [comment]
weewx does work with the access, but the access must send data in wu format.  configure the access to send wu data.  ideally you would configure it to send to the computer running weewx (use dns hijacking for this).  then configure interceptor to listen (not sniff), and it will simply receive the wu data.

if you prefer to send to wu, then you must configure the interceptor to sniff the traffic (not listen).

please post on the weewx user group for further help on this.

i am sorry there is not yet a guide specifically for intercepter and access

**Comment by ZXant** [comment]
Thanks Matthew for your time and prompt response. Will try.
