### ISSUE TITLE
Promiscuous mode needs to be enabled

### ISSUE THREAD

**Issue by vk4tdi** [matthewwall/weewx-interceptor#59]
Hi,

I've had to rebuild my server and have started from scratch with WeeWx and Interceptor again. I had problems getting interceptor.py to notice any packets in sniff mode, even though tshark was working fine.

I've gone into the python and see that the default for 'promiscuous' is 0. I hard coded it to 1 and it got things working. I've now put it back to 0 and found that 'promiscuous=1' in weewx.conf works too.

I couldn't find any mention of this in the documentation. Is this something you can add into the 'sniff' part of the documents? I can't remember how to propose changes, so sorry for the cop-out.

Cheers,
   David.

**Comment by matthewwall** [comment]
added to the default stanza at commit 405a613
