### ISSUE TITLE
pcapObject_open_live error

### ISSUE THREAD

**Issue by sgrayban** [matthewwall/weewx-interceptor#61]
weewx won't run. Getting this in the error logs.
`Import of driver failed: in method 'pcapObject_open_live', argument 2 of type 'char *' (<type 'exceptions.TypeError'>)`

**Comment by matthewwall** [comment]
this is being addressed in the weewx-user group

https://groups.google.com/forum/#!topic/weewx-user/5YIdQdPwlx0
