### ISSUE TITLE
question:  Acurite Access - does it contain a barometer sensor?

### ISSUE THREAD

**Issue by mrneutron42** [matthewwall/weewx-interceptor#93]
I recently bought an Acurite Atlas.  Yesterday, I learned that the outdoor Atlas sensor unit does not include a barometer sensor.
Acurite puts the barometer sensor inside their indoor display units.
I had been hoping to use the weewx-sdr to catch all the data (including barometer).

I wonder if the Acurite Access unit has a barometer sensor inside?

**Comment by rct** [comment]
Yes, the Acurite Access box has the barometer sensor inside. None of their outdoor weather stations have a barometer in them.

**Comment by rct** [comment]
I wouldn't purchase an Acurite Access just for pressure.  

With the Access you get 5 minute reports instead of the real time updates you are seeing now with rtl_433.

I haven't seriously looked for a 433mhz barometer in a while.  I've seen a bunch of people that just connect a pressure sensor (bosch IIRC) to an RPI. 

I do have an Access, because I got that cheap upgrade from the old smarthub, so I do get pressure from it.  Interestingly it gives readings that are close enough to what I get from the closest airport.  Where the local sensor wins out is when something the readings are dropping fast.

**Comment by mrneutron42** [comment]
How can you import airport barometric pressure readings into weewx?

I did some searches and didn't find any USB barometer or pressure sensors.
I did find several Adafruit PCBs with pressure sensors on them.  But, they have i2c or SPI interfaces, not USB.
https://www.adafruit.com/category/114

**Comment by rct** [comment]
> How can you import local airport barometric pressure readings into weewx?

Sorry for the confusing, the above screenshots are from Home Assistant. I'm using weather integrations in Home Assistant to poll the US National Weather Service for the closest airport observations (and forecasts).  I'm also pulling some other weather data from Open Weather Map and Dark Sky (until it goes away).

Home Assistant pushes data to MQTT and InfluxDB. However I'm not currently publishing to WeeWX, I've been using Home Assistant as my primary real time console. I also have rtl_433 publishing directly to MQTT, which is how I get that data to Home Assistant and anything else that wants to consume it.  I thought I saw there may be an MQTT option for weewx, but not sure if that is for consuming data or publishing data.  

Yes, the sensors that I've seen connected to an RPI use I2C or SPI.  I haven't seen a USB interfaced version. I think I picked up one of the Adafruit sensors but never got around to hooking it up to a RPI.  Looks straightforward, but I'm currently getting pressure in 5 minute updates from the Acurite Access, though I'd like to eliminate the dependency on that some day.

**Comment by mrneutron42** [comment]
I just put together a barometer that can feed WeeWX, using a BMP280 i2c pressure sensor + ESP-12F dev board + Tasmota firmware + MQTT + MQTTSubscribe add-on for WeeWX!
Getting the MQTTSubscribe set up was one of the hardest parts.  I got crucial advice on the weewx-user Google Group and that me over the hump! 
![PXL_20210513_203224524 (Custom)](https://user-images.githubusercontent.com/70338169/118189589-999e6f00-b407-11eb-8499-9841d5165406.jpg)
![Tasmota reading BMP280 pressure sensor](https://user-images.githubusercontent.com/70338169/118189707-bcc91e80-b407-11eb-9723-f1602a56d5ad.JPG)
